# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `bin/rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Although this is not needed for an API-only application, Rails
# shares cookies, signing and encrypted data amongst
# different domains. If you don't share cookies with other apps,
# you can delete this file.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default

# DO NOT store production secrets in this file.
# Instead, read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> 